name: iq
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  get: ^4.6.5
  shared_preferences: ^2.0.16

  flutter_svg: ^2.0.0+1

  intl: 
  timeago:
  google_fonts: ^4.0.3  

  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  firebase_storage: ^11.0.10
  firebase_dynamic_links: ^5.0.11
  cloud_firestore: ^4.3.1

  url_launcher: ^6.1.9
  share_plus: ^6.3.1
  image_picker: ^0.8.6+1

  # read_more_text: ^0.0.5
  read_more_text:
    path: read_more_text/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: 

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

   # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans/OpenSans-BoldItalic.ttf
        - asset: assets/fonts/OpenSans/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/OpenSans/OpenSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Italic.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans/OpenSans-LightItalic.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Medium.ttf
        - asset: assets/fonts/OpenSans/OpenSans-MediumItalic.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans/OpenSans-SemiBold.ttf
        - asset: assets/fonts/OpenSans/OpenSans-SemiBoldItalic.ttf
  #         style: italic
    - family: Colaberate
      fonts:
        - asset: assets/fonts/Colaberate/ColabBol.otf
        - asset: assets/fonts/Colaberate/ColabLig.otf
        - asset: assets/fonts/Colaberate/ColabMed.otf
        - asset: assets/fonts/Colaberate/ColabReg.otf
        - asset: assets/fonts/Colaberate/ColabThi.otf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
